openapi: 3.0.0
info:
  title: campaign
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/v1/campaign/{campaignId}':
    parameters:
      - schema:
          type: string
        name: campaignId
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      operationId: get-users-userId
      description: Retrieve the information of the campaign with the matching campaign ID.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/campaign'
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    status: 0
                    create: '2019-08-24T14:15:22Z'
                    update: '2019-08-24T14:15:22Z'
        '404':
          $ref: '#/components/responses/404_not_found'
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: Campaign Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/campaign'
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    status: 0
                    create: '2019-08-24T14:15:22Z'
                    update: '2019-08-24T14:15:22Z'
        '404':
          $ref: '#/components/responses/404_not_found'
      description: Update the infromation of an existing campaign.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            examples:
              example-1:
                value:
                  name: string
        description: ''
  /api/v1/campaign:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: Campaign Created
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/campaign'
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    status: 0
                    create: '2019-08-24T14:15:22Z'
                    update: '2019-08-24T14:15:22Z'
        '422':
          description: Missing Required Information
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                  fields:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              minLength: 1
                            message:
                              type: string
                              minLength: 1
                          required:
                            - code
                            - message
                required:
                  - message
                  - fields
              examples:
                error message:
                  value:
                    message: 字段校验失败
                    fields:
                      name:
                        - code: invalid
                          message: 已存在同名任务，请使用其他名称
      requestBody:
        content:
          application/xml:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
                - name
            examples:
              example-1:
                value:
                  name: string
        description: Post the necessary fields for the API to create a new user.
      description: Create a new campaign.
    parameters: []
    get:
      summary: ''
      operationId: get-task-precampaign
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      parameters:
        - schema:
            type: integer
            enum:
              - 0
              - 1
              - 2
          in: query
          name: status
          description: campaign 状态
        - schema:
            type: string
          in: query
          name: orderColumn
          description: 排序字段
        - schema:
            type: string
            enum:
              - asc
              - desc
          in: query
          name: orderType
          description: 排序类型
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    type: array
                    items:
                      $ref: '#/components/schemas/campaign'
                  page:
                    $ref: '#/components/schemas/Page'
              examples:
                example-2:
                  value:
                    record:
                      - id: 0
                        name: string
                        status: 0
                        create: '2019-08-24T14:15:22Z'
                        update: '2019-08-24T14:15:22Z'
                    page:
                      current: 0
                      size: 0
                      total: 0
        '403':
          $ref: '#/components/responses/403_forbidden'
components:
  schemas:
    campaign:
      description: ''
      type: object
      x-examples:
        example-2:
          id: 0
          name: string
          status: 0
          create: '2020-12-31'
          update: '2020-12-31'
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        status:
          type: integer
        create:
          type: string
          format: date-time
        update:
          type: string
          format: date-time
      required:
        - id
        - name
        - status
        - create
        - update
    Page:
      description: ''
      type: object
      properties:
        current:
          type: number
        size:
          type: number
        total:
          type: number
      required:
        - current
        - size
        - total
  responses:
    200_ok:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              record:
                type: array
                items:
                  type: object
              page:
                type: object
                properties:
                  current:
                    type: integer
                  size:
                    type: integer
                  total:
                    type: integer
          examples:
            example-1:
              value:
                record:
                  - {}
                page:
                  current: 0
                  size: 0
                  total: 0
    404_not_found:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
            required:
              - message
          examples:
            example-1:
              value:
                message: 无权访问
    403_forbidden:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
            required:
              - message
          examples:
            example-1:
              value:
                message: string
